# Generated by Django 5.0.4 on 2024-05-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="description",
            field=models.TextField(default="no description", max_length=500),
            preserve_default=False,
        ),
    ]
