# Generated by Django 5.0.4 on 2024-05-09 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pet",
            name="owner_id",
        ),
    ]
